[tool.black]
line-length = 80

[tool.ruff.lint]
select = ["D"]

ignore = ["D100", "D102", "D104", "D105", "D107", "D203", "D213", "D401", "D402"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
preview = true
docstring-code-format = true
docstring-code-line-length = 20

